platzigram/urls.py
"""Platzigram URLs module."""

# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Posts URLs."""

# Django
from django.urls import path

# Views
from posts import views

urlpatterns = [

    path(
        route='',
        view=views.PostsFeedView.as_view(),
        name='feed'
    ),
   

    path(
        route='posts/new/',
        view=views.CreateMausoleoView.as_view(),
        name='create'
    ),

    path(
        route='posts/<int:pk>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),
     path(
        route='posts/qr/<int:pk>',
        view=views.QRView.as_view(),
        name='qr'
    ),
]

posts/models.py
"""Posts models."""

# Django
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    """Post model."""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey('users.Profile', on_delete=models.CASCADE)

    title = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='posts/photos')

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return title and username."""
        return '{} by @{}'.format(self.title, self.user.username)

class Mausoleo(models.Model):
    """Post model."""


    nombre = models.CharField(max_length=255)
    descripcion = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='posts/photos')

  

posts/forms.py
"""Post forms."""

# Django
from django import forms

# Models
from posts.models import Post, Mausoleo


class PostForm(forms.ModelForm):
    """Post model form."""

    class Meta:
        """Form settings."""

        model = Post
        fields = ('user', 'profile', 'title', 'photo')


class MausoleoForm(forms.ModelForm):
    """Post model form."""

    class Meta:
        """Form settings."""

        model = Mausoleo
        fields = ('nombre', 'descripcion', 'photo')

posts/views.py
"""Posts views."""

# Django
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, ListView

# Forms
from posts.forms import PostForm, MausoleoForm

# Models
from posts.models import Post, Mausoleo

class CreateMausoleoView(CreateView):
    """Create a new post."""

    template_name = 'posts/createmausoleo.html'
    form_class = MausoleoForm
    success_url = reverse_lazy('posts:feed')


class PostsFeedView(ListView):
    """Return all published posts."""

    template_name = 'posts/feed.html'
    model = Mausoleo
    context_object_name = 'posts'

class QRView(DetailView):
    """Return all published posts."""

    template_name = 'posts/qr.html'
    queryset = Mausoleo.objects.all()
    context_object_name = 'maus'


class PostDetailView(DetailView):
    """Return post detail."""

    template_name = 'posts/index.html'
    queryset = Mausoleo.objects.all()
    context_object_name = 'maus'


class CreatePostView(LoginRequiredMixin, CreateView):
    """Create a new post."""

    template_name = 'posts/createmausoleo.html'
    form_class = PostForm
    success_url = reverse_lazy('posts:feed')

    def get_context_data(self, **kwargs):
        """Add user and profile to context."""
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['profile'] = self.request.user.profile
        return context

templates/posts/createmausoleo.html
{% extends "base.html" %}

{% block head_content %}
<title>Agregar mausoleo</title>
{% endblock %}

{% block container %}

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-6 pt-3 pb-3" id="profile-box">
                <h4 class="mb-4">Agregar nuevo mausoleo</h4>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    

                    {# Website field #}
                    <div class="form-group">
                        <input
                            type="text"
                            name="nombre"
                            placeholder="Nombre"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>
                    {# Website field #}
                    <div class="form-group">
                        <input
                            type="text"
                            name="descripcion"
                            placeholder="Descripcion"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    {# Photo field #}
                    <div class="form-group">
                        <label>Elige la foto:</label>
                        <input
                            class="form-control {% if form.photo.errors %}is-invalid{% endif %}"
                            type="file"
                            name="photo"
                            placeholder="Foto"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.photo.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block mt-5">Agregar</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/posts/detail.html
{% extends "base.html" %}

{% block head_content %}
    <title>Platzigram</title>
{% endblock%}
<!DOCTYPE html>
{% block container %}

    <div class="container">
        <div class="row">
            {% include "posts/post_card.html" %}
        </div>
    </div>

{% endblock %}

templates/posts/feed.html
{% extends "base.html" %}

{% block head_content %}
    <title>Platzigram</title>
{% endblock%}

{% block container %}

    <div class="container">
        <div class="row">

            {% for post in posts %}
                {% include "posts/post_card.html" %}
            {% endfor %}
        </div>
    </div>

    {% include "pagination.html" %}

{% endblock %}

templates/posts/index.html
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Product Card/Page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
  </head>
  <body>
    
    <div class = "card-wrapper">
      <div class = "card">
        <!-- card left -->
        <div class = "product-imgs">
          <div class = "img-display">
            <div class = "img-showcase">
              <img src = "{{ maus.photo.url }}">
            </div>
          </div>
          <div class = "img-select">
          </div>
        </div>
        
        <!-- card right -->
        <div class = "product-content">
          <div class="logo">
            <object type="image/svg+xml" data="{% static 'img/logo.svg' %}" width="100" height="100">
            </object>
          </div>
          <h2 class = "product-title">{{maus.nombre}}</h2>
          <div class = "product-rating">
          </div>

          <div class = "product-price">
          </div>
          

          <div class = "product-detail">
            <h2>{{maus.descripcion}}</h2>
          
          </div>

          

        </div>
      </div>
    </div>

    
    <script src="script.js"></script>
  </body>
</html>

templates/posts/new.html
{% extends "base.html" %}

{% block head_content %}
<title>Create new post</title>
{% endblock %}

{% block container %}

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-6 pt-3 pb-3" id="profile-box">
                <h4 class="mb-4">Post a new photo!</h4>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <input type="hidden" name="user" value="{{ user.pk}}" />
                    <input type="hidden" name="profile" value="{{ profile.pk }}" />

                    {# Website field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.title.errors %}is-invalid{% endif %}"
                            type="text"
                            name="title"
                            placeholder="Title"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    {# Photo field #}
                    <div class="form-group">
                        <label>Choose your photo:</label>
                        <input
                            class="form-control {% if form.photo.errors %}is-invalid{% endif %}"
                            type="file"
                            name="photo"
                            placeholder="photo"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.photo.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block mt-5">Publish!</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/posts/post_card.html
<div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
    <div class="media pt-3 pl-3 pb-1">

        <div class="media-body">
          
        </div>
    </div>

    <img style="width: 100%;" src="{{ post.photo.url }}" alt="{{ post.nombre }}">

    <p class="mt-1 ml-2" >
        <a href="" style="color: #000; font-size: 20px;">
           
        </a> 
    </p>
    <p class="ml-2 mt-0 mb-2">
        <b>{{ post.nombre }}</b> - 
        <button><a href="{% url 'posts:qr' post.pk %}">Ver QR</a></button>
        <button><a href="">Ver Descripcion</a></button>
</div>

templates/posts/qr.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    </html>
<script src="https://cdn.jsdelivr.net/gh/davidshimjs/qrcodejs/qrcode.min.js"></script>

</head>
<body>


<div id="qrcode"></div>
    <script>
        const full_url = "{{request.build_absolute_uri}}";
        console.log(full_url)
        let splice_url = full_url.split('/').splice(2,2);
        let new_url = splice_url.join('/')
        console.log(splice_url)
    var url= `${new_url}/{{maus.pk}}`;
        const qrcode = new QRCode(document.getElementById('qrcode'), {
            text: url,
            width: 128,
            height: 128,
            colorDark : '#000',
            colorLight : '#fff',
            correctLevel : QRCode.CorrectLevel.H
          });
        </script>        
</body>
</html>